#!/usr/bin/env bash

URL="https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main"
case "$1" in
  '-t'|'template'|'convert')
	while [ -n "$1" ]
	do
	rm -f /opt/github2am/download-args
	echo $@ | tr ' ' '\n' >> /opt/github2am/download-args && echo STOP >> /opt/github2am/download-args
	ARGS=$(sed '1d' /opt/github2am/download-args)
	for arg in $ARGS; do
	for var in $arg; do
	if [ $arg == STOP ]; then
	exit
	else
	case $arg in
	*) for var in $arg
	do
	cd $(xdg-user-dir DESKTOP)
	mkdir -p am-scripts && cd am-scripts
	mkdir -p ABOUT
	REPO=$( echo $arg )
	USER=$(echo $REPO | sed 's:/[^/]*$::')
	REPO2=$(echo $REPO | sed 's:.*/::')
	APP=$( echo $REPO2 | tr A-Z a-z | sed s/_/-/g )
	COMMENT=$(curl https://api.github.com/repos/$REPO 2>/dev/null | grep description | sed 's/"description": "//' | sed 's/",//')
	REPO=$(curl -L -s https://raw.githubusercontent.com/AppImage/appimage.github.io/master/apps/$arg.md | grep -A1 "type: GitHub" | sed -n 2p | cut -c 10-)
	wget -c $URL/templates/AM-SAMPLE-GitHub-generic -O $APP
	sed -i s/SAMPLE/$APP/g $APP
	sed -i s#REPLACETHIS#$arg#g $APP
	chmod a+x $APP
	echo " " >> ./ABOUT/$APP 
	echo " $COMMENT" >> ./ABOUT/$APP 
	echo " " >> ./ABOUT/$APP 
	echo " SITE: https://github.com/$REPO" >> ./ABOUT/$APP 
	echo '◆ '$APP' : '$COMMENT'' >> ./list
	echo " ------------------------------------------------
	
	CREATING A SCRIPT FOR "$APP"
	" | tr a-z A-Z
	echo " ------------------------------------------------"
	echo "" 
	echo " LIST OF CATEGORIES:

	0)  AudioVideo	 
	1)  Audio
	2)  Video
	3)  Development
	4)  Education
	5)  Game
	6)  Graphics	 
	7)  Network
	8)  Office
	9)  Science
	10) Settings
	11) System
	12) Utility (default)

	"
	read -r -p " CHOOSE A CATEGORY : " response
	case "$response" in
	0) sed -i s/YOURCATEGORY/AudioVideo/g $APP;;	 
	1) sed -i s/YOURCATEGORY/Audio/g $APP;;
	2) sed -i s/YOURCATEGORY/Video/g $APP;;
	3) sed -i s/YOURCATEGORY/Development/g $APP;;
	4) sed -i s/YOURCATEGORY/Education/g $APP;;
	5) sed -i s/YOURCATEGORY/Game/g $APP;;
	6) sed -i s/YOURCATEGORY/Graphics/g $APP;;
	7) sed -i s/YOURCATEGORY/Network/g $APP;;
	8) sed -i s/YOURCATEGORY/Office/g $APP;;
	9) sed -i s/YOURCATEGORY/Science/g $APP;;
	10) sed -i s/YOURCATEGORY/Settings/g $APP;;
	11) sed -i s/YOURCATEGORY/System/g $APP;;
	12|*) sed -i s/YOURCATEGORY/Utility/g $APP;;
	esac

	echo "" 
	read -r -p " COPY THE LINK URL TO THE ICON AND PASTE IT HERE : " RESPONSE
	case "$RESPONSE" in
    	*) sed -i s#YOURICONURL#$RESPONSE#g $APP;;
	esac

	done
	break
	esac
	fi
	done
	done
	done
	shift;;
   *) echo ""; echo ' USAGE: github2am convert $USER/$REPO'; echo ""
 	echo ' where $USER/$REPO is the name of repository where the app is hosted.'; echo "";;
esac
